// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw1XV8ca8F-bmlfO6iw68mtFwMVxg0ScE',
    appId: '1:782864972778:web:4c7df82c1726e36a0f1093',
    messagingSenderId: '782864972778',
    projectId: 'app-bottom-navigation-b9ca6',
    authDomain: 'app-bottom-navigation-b9ca6.firebaseapp.com',
    storageBucket: 'app-bottom-navigation-b9ca6.firebasestorage.app',
    measurementId: 'G-EJRBEJ78WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoGW2CSaknaC7Wu2As-sWMFgSIJacQcV0',
    appId: '1:782864972778:android:b7de92c6b4b13fe40f1093',
    messagingSenderId: '782864972778',
    projectId: 'app-bottom-navigation-b9ca6',
    storageBucket: 'app-bottom-navigation-b9ca6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw1XV8ca8F-bmlfO6iw68mtFwMVxg0ScE',
    appId: '1:782864972778:web:181d34c3d888db2a0f1093',
    messagingSenderId: '782864972778',
    projectId: 'app-bottom-navigation-b9ca6',
    authDomain: 'app-bottom-navigation-b9ca6.firebaseapp.com',
    storageBucket: 'app-bottom-navigation-b9ca6.firebasestorage.app',
    measurementId: 'G-J6SCQTQ6KY',
  );
}
